button
alvaroscelza/Claims-and-Complaints pull request #96
Opened 2024-01-18 20:19 UTC by federicosilvera

2024-01-28 21:52 UTC, alvaroscelza requested changes

2024-01-28 21:52 UTC, alvaroscelza commented on applications/core/urls.py
no hagas los links aca, fijate como esta en el otro proyecto, estan en el arhivo url original, de hecho vas a ver que hay codigo comentado ahi, usalo

2024-01-28 21:52 UTC, alvaroscelza commented on applications/core/templates/sugerencia.html
no necesitamos este archivo, mete el boton en el archivo main

2024-01-28 21:52 UTC, alvaroscelza commented on applications/core/views.py
no precisas un archivo views, fijate como est aen el otro proyecto

2024-01-28 21:52 UTC, alvaroscelza commented on config/settings.py
bajate los ultimos cambios, estos cambios de aca tan turbios

2024-01-28 21:52 UTC, alvaroscelza commented on static/contacto.css
contacto es en es;aol, usa contact

2024-01-29 04:37 UTC, federicosilvera commented on applications/core/views.py
esto fue lo unico que me genero duda creo, borre el archivo views, pero coloque mi vista en una carpeta controller views que tenias, no se si era eso

2024-02-03 02:11 UTC, alvaroscelza requested changes

2024-02-03 02:11 UTC, alvaroscelza commented on applications/core/urls.py
> +
aca agregaste una linea en balcno que no se precisa.

2024-02-03 02:11 UTC, alvaroscelza commented on config/settings.py
> +
Borra estas dos lineas en blanco que agregaste

2024-02-03 02:11 UTC, alvaroscelza commented on config/urls.py
> +urlpatterns += i18n_patterns(contact_template, prefix_default_language=False)
No precisas agregar un endpoint para esto, fijate como esta la linea de abajo que saque del otro proyecto:

`contact_template = TemplateView.as_view(template_name='contact.html')`

Averigua como funciona el TemplateView en Django

2024-02-03 02:11 UTC, alvaroscelza commented on templates/layouts/header.html
> +
esta linea no va

2024-02-03 02:11 UTC, alvaroscelza commented on templates/layouts/main.html
> +    <main class="container pt-4" >
agregas un espacio en blanco al final que no va

2024-02-07 00:45 UTC, alvaroscelza requested changes

2024-02-07 00:45 UTC, alvaroscelza commented on applications/core/urls.py
> -
por que borrar esta linea? pycharm separa los imports de terceros de los internos.

2024-02-07 00:45 UTC, alvaroscelza commented on config/settings.py
> +               'django.contrib.staticfiles']
por que este cambio?

2024-02-08 23:42 UTC, alvaroscelza requested changes

2024-02-08 23:42 UTC, alvaroscelza commented on config/urls.py
>  # urlpatterns += i18n_patterns(path(r'contact/', contact_template), prefix_default_language=False)
estas dos lineas comentadas borralas no mas porque ya las pusiste arriba.

2024-02-09 00:54 UTC, alvaroscelza approved these changes

2024-02-09 00:54 UTC, merged